### ISSUE TITLE
On_release.yml workflow file does not run automatically based on webhook event generated from on_pr_master.yml 

### ISSUE THREAD

**Issue by fredrikhgrelland** [fredrikhgrelland/vagrant-hashistack#215]
Related to #217

**Comment by zhenik** [comment]
Actions used 
https://github.com/marketplace/actions/create-a-release 

https://developer.github.com/webhooks/event-payloads/

**Comment by Neha-Sinha2305** [comment]
Looks like this is the expected behaviour as per the github documentaion [triggering-new-workflows-using-a-personal-access-token](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token)

_There is a limitation of workflow: An action in a workflow run can’t trigger a new workflow run._

```
Triggering new workflows using a personal access token
When you use the repository's GITHUB_TOKEN to perform tasks on behalf of the GitHub Actions app, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur. For more information, see "Authenticating with the GITHUB_TOKEN."

If you would like to trigger a workflow from a workflow run, you can trigger the event using a personal access token. You'll need to create a personal access token and store it as a secret. To minimize your GitHub Actions usage costs, ensure that you don't create recursive or unintended workflow runs. For more information, see "Creating and storing encrypted secrets."
```
Some other links that hold useful information with regards to this:

1. https://github.com/actions/create-release/issues/20
2. https://github.com/actions/create-release/issues/52
