### ISSUE TITLE
Prefix `pr/` on release labels cause failure

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#330]
https://github.com/fredrikhgrelland/vagrant-hashistack/runs/1111332600?check_suite_focus=true

**Comment by pdmthorsrud** [comment]
Damn. I tested earlier, it looked like it was running fine. I obviously did that wrong, sorry!

**Comment by zhenik** [comment]
> Damn. I tested earlier, it looked like it was running fine. I obviously did that wrong, sorry!

Dont think its ur fault. We have some issues on release process.

**Comment by Neha-Sinha2305** [comment]
I looked at the [semver-release-action code](https://github.com/zwaldowski/semver-release-action) in order to find out why it failed for the  label  *pr/patch* . 

I suspect that the failure/exception is generated at the semver library(https://github.com/npm/node-semver) where it tries to match for exact string **patch** in the switch case:
https://github.com/npm/node-semver/blob/60880700d6cee8450e37f5ac31430d84587620f5/classes/semver.js#L240
The above function is called at the following line from the semver-release-action :  https://github.com/zwaldowski/semver-release-action/blob/c0ec75263ee9c881e686cf7fbe46d463391a3dac/index.js#L85
```
version = semver.inc(latestTag, bump, identifier)
```
So, we will need to live with the labels "patch,minor,major".
