### ISSUE TITLE
Shouldn't the default values in .env_default.j2 file be same as what it is going to be in minerva

### ISSUE THREAD

**Issue by Neha-Sinha2305** [fredrikhgrelland/vagrant-hashistack#377]
Since vagrant-box is primarily going to be used to provide development env for developing modules that could be run/ported easily to minerva so I am left to  thinking why we don't have the default values set according to minerva usage:

Currently, default env file looks like this:
https://github.com/fredrikhgrelland/vagrant-hashistack/blob/47d38018a42aa57fbd99ee2e4c3d3b5c8fc70155/ansible/templates/.env_default.j2#L1-L15

Wouldn't it be useful to have the following instead -
```
{% raw -%}
# Control box features
consul_enterprise=true
nomad_enterprise=true
vault_enterprise=true
consul_acl=true
consul_acl_default_policy=deny
nomad_acl=true
vault_pki=true
```
Note: This would also enable seamless testing in gitlab as the default env would comply with minerva. Currently they might need to add extra code to override the default .env values.

**Comment by Neha-Sinha2305** [comment]
@zhenik @pdmthorsrud : What are your thoughts on this?

**Comment by pdmthorsrud** [comment]
Hm, I'm glad you're bringing this up, because it is a good point.

I've been thinking of the vagrant-box as a place to learn and develop terraform modules within a hashistack ecosystem (and not necessarily Minerva's ecosystem). In that case I imagine the box should ship default with the simplest configuration it can have, and then have tests on OUR platform (gitlab/github) that notify you if it isn't compatible with Minerva.

Another perspective is that the box is meant as a testing ground for Minerva that just so happens to be a box you can use for learning and using the hashistack as well. In that case what you are proposing makes sense.

I'll admit I like the first one better, in that case we are making something bigger than just Minerva. If we develop with the mindset "a generic hashistack ecosystem" that just so happens to be able to be tweaked as to simulate Minerva that is way cooler IMO, because then we keep the open-source part of this. If we gear it towards Minerva as a default it isn't an open source project anymore

**Comment by zhenik** [comment]
I agree with @pdmthorsrud about 

> "a generic hashistack ecosystem"

I won't recommend have config coupling with minerva. It might bring 'fake' simplicity to people from minerva and vice-versa for new comers to try the vagrant-hashistack (due to default startup is `ent` editions for consul and vault)

**Comment by pdmthorsrud** [comment]
I'm closing this. Neha, please reopen if you feel this is still a question to be answered.
